//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Scripts/Input/AccionesNinten.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Input/AccionesNinten.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @AccionesNinten: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @AccionesNinten()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""AccionesNinten"",
    ""maps"": [
        {
            ""name"": ""MapaAccionesNinten"",
            ""id"": ""fad558bc-7219-4de3-9b63-3404a40330a7"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""9eb7fea1-4009-4ece-b03c-40b8a033a5c1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SaltoInteraccionConfirmar"",
                    ""type"": ""Button"",
                    ""id"": ""6067ce24-a1d8-4d0a-8d04-f34074c122f4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DistanciaCancelar"",
                    ""type"": ""Button"",
                    ""id"": ""0cf24b1e-cfe3-4c35-b7d9-c0748c4c11a5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Magia"",
                    ""type"": ""Button"",
                    ""id"": ""43192ada-a35d-4618-8f57-cf8a5e3949d7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Atacar"",
                    ""type"": ""Button"",
                    ""id"": ""e78af798-16fd-4da6-91ba-4d7f7ded7947"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escudo"",
                    ""type"": ""Button"",
                    ""id"": ""1a14c732-f21e-428c-8b12-01897490ee6d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FijarDisparar"",
                    ""type"": ""Button"",
                    ""id"": ""87a107a5-2c49-47fd-bbf9-bfa8f3f6e29e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camara"",
                    ""type"": ""Value"",
                    ""id"": ""fb5db63d-0a70-46e8-945f-46b265eb4d34"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pausa"",
                    ""type"": ""Button"",
                    ""id"": ""4f48af4f-217b-4570-9ed9-23edcf41cef5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""50a01573-a79b-437e-baac-209fa4ac5fbf"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d420d5de-ec68-42a4-b6de-9b38a3f31cd8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""08008f0a-613d-4a7d-9c5d-2707a65b093e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5515f336-4560-4209-ae5d-cec3656090ad"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""17fa21f1-c8f4-46af-a829-345b0230c343"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5bd63743-96d6-4076-a949-faf97b375fac"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0943ef2a-f34a-47a5-b92c-9d1a4fb45d9a"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaltoInteraccionConfirmar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8dfb42a4-a4cf-4a88-8293-554c7d1d67ee"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaltoInteraccionConfirmar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6c6ce38-c80f-4bde-b603-e606d58a4769"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DistanciaCancelar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b94810af-f8b6-4c4b-91b6-2a1430c3719b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DistanciaCancelar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38b57bb8-b02c-4aca-a794-d0bd756a252d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magia"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""254fc9b8-3563-4d56-baa7-03dba6c052ad"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Magia"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49e41aa4-f784-45cc-849f-136afa2821d3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa9f3e1a-6f4c-470b-849e-f78532c86685"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Atacar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""052a4cba-67c7-46b1-a9eb-29f50db76fd7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escudo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9494b8ba-ef68-4261-9094-8c45ce7a9244"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escudo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ee42ded-1dae-471d-9f08-43637a467154"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FijarDisparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3455052-441a-418a-9ba6-a62a22144337"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FijarDisparar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f5880a5-33fe-4381-a349-1901a6e2c173"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camara"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38edfe77-6b7e-4175-ae0a-af7c0d5b3820"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camara"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""badf3dae-153d-41ef-a810-ef7a5944eafa"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cd6403e-f8b5-4321-b52e-50cdbe43e05b"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pausa"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MapaAccionesNinten
        m_MapaAccionesNinten = asset.FindActionMap("MapaAccionesNinten", throwIfNotFound: true);
        m_MapaAccionesNinten_Movimiento = m_MapaAccionesNinten.FindAction("Movimiento", throwIfNotFound: true);
        m_MapaAccionesNinten_SaltoInteraccionConfirmar = m_MapaAccionesNinten.FindAction("SaltoInteraccionConfirmar", throwIfNotFound: true);
        m_MapaAccionesNinten_DistanciaCancelar = m_MapaAccionesNinten.FindAction("DistanciaCancelar", throwIfNotFound: true);
        m_MapaAccionesNinten_Magia = m_MapaAccionesNinten.FindAction("Magia", throwIfNotFound: true);
        m_MapaAccionesNinten_Atacar = m_MapaAccionesNinten.FindAction("Atacar", throwIfNotFound: true);
        m_MapaAccionesNinten_Escudo = m_MapaAccionesNinten.FindAction("Escudo", throwIfNotFound: true);
        m_MapaAccionesNinten_FijarDisparar = m_MapaAccionesNinten.FindAction("FijarDisparar", throwIfNotFound: true);
        m_MapaAccionesNinten_Camara = m_MapaAccionesNinten.FindAction("Camara", throwIfNotFound: true);
        m_MapaAccionesNinten_Pausa = m_MapaAccionesNinten.FindAction("Pausa", throwIfNotFound: true);
    }

    ~@AccionesNinten()
    {
        UnityEngine.Debug.Assert(!m_MapaAccionesNinten.enabled, "This will cause a leak and performance issues, AccionesNinten.MapaAccionesNinten.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MapaAccionesNinten
    private readonly InputActionMap m_MapaAccionesNinten;
    private List<IMapaAccionesNintenActions> m_MapaAccionesNintenActionsCallbackInterfaces = new List<IMapaAccionesNintenActions>();
    private readonly InputAction m_MapaAccionesNinten_Movimiento;
    private readonly InputAction m_MapaAccionesNinten_SaltoInteraccionConfirmar;
    private readonly InputAction m_MapaAccionesNinten_DistanciaCancelar;
    private readonly InputAction m_MapaAccionesNinten_Magia;
    private readonly InputAction m_MapaAccionesNinten_Atacar;
    private readonly InputAction m_MapaAccionesNinten_Escudo;
    private readonly InputAction m_MapaAccionesNinten_FijarDisparar;
    private readonly InputAction m_MapaAccionesNinten_Camara;
    private readonly InputAction m_MapaAccionesNinten_Pausa;
    /// <summary>
    /// Provides access to input actions defined in input action map "MapaAccionesNinten".
    /// </summary>
    public struct MapaAccionesNintenActions
    {
        private @AccionesNinten m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MapaAccionesNintenActions(@AccionesNinten wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Movimiento".
        /// </summary>
        public InputAction @Movimiento => m_Wrapper.m_MapaAccionesNinten_Movimiento;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/SaltoInteraccionConfirmar".
        /// </summary>
        public InputAction @SaltoInteraccionConfirmar => m_Wrapper.m_MapaAccionesNinten_SaltoInteraccionConfirmar;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/DistanciaCancelar".
        /// </summary>
        public InputAction @DistanciaCancelar => m_Wrapper.m_MapaAccionesNinten_DistanciaCancelar;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Magia".
        /// </summary>
        public InputAction @Magia => m_Wrapper.m_MapaAccionesNinten_Magia;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Atacar".
        /// </summary>
        public InputAction @Atacar => m_Wrapper.m_MapaAccionesNinten_Atacar;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Escudo".
        /// </summary>
        public InputAction @Escudo => m_Wrapper.m_MapaAccionesNinten_Escudo;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/FijarDisparar".
        /// </summary>
        public InputAction @FijarDisparar => m_Wrapper.m_MapaAccionesNinten_FijarDisparar;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Camara".
        /// </summary>
        public InputAction @Camara => m_Wrapper.m_MapaAccionesNinten_Camara;
        /// <summary>
        /// Provides access to the underlying input action "MapaAccionesNinten/Pausa".
        /// </summary>
        public InputAction @Pausa => m_Wrapper.m_MapaAccionesNinten_Pausa;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MapaAccionesNinten; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MapaAccionesNintenActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MapaAccionesNintenActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MapaAccionesNintenActions" />
        public void AddCallbacks(IMapaAccionesNintenActions instance)
        {
            if (instance == null || m_Wrapper.m_MapaAccionesNintenActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MapaAccionesNintenActionsCallbackInterfaces.Add(instance);
            @Movimiento.started += instance.OnMovimiento;
            @Movimiento.performed += instance.OnMovimiento;
            @Movimiento.canceled += instance.OnMovimiento;
            @SaltoInteraccionConfirmar.started += instance.OnSaltoInteraccionConfirmar;
            @SaltoInteraccionConfirmar.performed += instance.OnSaltoInteraccionConfirmar;
            @SaltoInteraccionConfirmar.canceled += instance.OnSaltoInteraccionConfirmar;
            @DistanciaCancelar.started += instance.OnDistanciaCancelar;
            @DistanciaCancelar.performed += instance.OnDistanciaCancelar;
            @DistanciaCancelar.canceled += instance.OnDistanciaCancelar;
            @Magia.started += instance.OnMagia;
            @Magia.performed += instance.OnMagia;
            @Magia.canceled += instance.OnMagia;
            @Atacar.started += instance.OnAtacar;
            @Atacar.performed += instance.OnAtacar;
            @Atacar.canceled += instance.OnAtacar;
            @Escudo.started += instance.OnEscudo;
            @Escudo.performed += instance.OnEscudo;
            @Escudo.canceled += instance.OnEscudo;
            @FijarDisparar.started += instance.OnFijarDisparar;
            @FijarDisparar.performed += instance.OnFijarDisparar;
            @FijarDisparar.canceled += instance.OnFijarDisparar;
            @Camara.started += instance.OnCamara;
            @Camara.performed += instance.OnCamara;
            @Camara.canceled += instance.OnCamara;
            @Pausa.started += instance.OnPausa;
            @Pausa.performed += instance.OnPausa;
            @Pausa.canceled += instance.OnPausa;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MapaAccionesNintenActions" />
        private void UnregisterCallbacks(IMapaAccionesNintenActions instance)
        {
            @Movimiento.started -= instance.OnMovimiento;
            @Movimiento.performed -= instance.OnMovimiento;
            @Movimiento.canceled -= instance.OnMovimiento;
            @SaltoInteraccionConfirmar.started -= instance.OnSaltoInteraccionConfirmar;
            @SaltoInteraccionConfirmar.performed -= instance.OnSaltoInteraccionConfirmar;
            @SaltoInteraccionConfirmar.canceled -= instance.OnSaltoInteraccionConfirmar;
            @DistanciaCancelar.started -= instance.OnDistanciaCancelar;
            @DistanciaCancelar.performed -= instance.OnDistanciaCancelar;
            @DistanciaCancelar.canceled -= instance.OnDistanciaCancelar;
            @Magia.started -= instance.OnMagia;
            @Magia.performed -= instance.OnMagia;
            @Magia.canceled -= instance.OnMagia;
            @Atacar.started -= instance.OnAtacar;
            @Atacar.performed -= instance.OnAtacar;
            @Atacar.canceled -= instance.OnAtacar;
            @Escudo.started -= instance.OnEscudo;
            @Escudo.performed -= instance.OnEscudo;
            @Escudo.canceled -= instance.OnEscudo;
            @FijarDisparar.started -= instance.OnFijarDisparar;
            @FijarDisparar.performed -= instance.OnFijarDisparar;
            @FijarDisparar.canceled -= instance.OnFijarDisparar;
            @Camara.started -= instance.OnCamara;
            @Camara.performed -= instance.OnCamara;
            @Camara.canceled -= instance.OnCamara;
            @Pausa.started -= instance.OnPausa;
            @Pausa.performed -= instance.OnPausa;
            @Pausa.canceled -= instance.OnPausa;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MapaAccionesNintenActions.UnregisterCallbacks(IMapaAccionesNintenActions)" />.
        /// </summary>
        /// <seealso cref="MapaAccionesNintenActions.UnregisterCallbacks(IMapaAccionesNintenActions)" />
        public void RemoveCallbacks(IMapaAccionesNintenActions instance)
        {
            if (m_Wrapper.m_MapaAccionesNintenActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MapaAccionesNintenActions.AddCallbacks(IMapaAccionesNintenActions)" />
        /// <seealso cref="MapaAccionesNintenActions.RemoveCallbacks(IMapaAccionesNintenActions)" />
        /// <seealso cref="MapaAccionesNintenActions.UnregisterCallbacks(IMapaAccionesNintenActions)" />
        public void SetCallbacks(IMapaAccionesNintenActions instance)
        {
            foreach (var item in m_Wrapper.m_MapaAccionesNintenActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MapaAccionesNintenActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MapaAccionesNintenActions" /> instance referencing this action map.
    /// </summary>
    public MapaAccionesNintenActions @MapaAccionesNinten => new MapaAccionesNintenActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MapaAccionesNinten" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MapaAccionesNintenActions.AddCallbacks(IMapaAccionesNintenActions)" />
    /// <seealso cref="MapaAccionesNintenActions.RemoveCallbacks(IMapaAccionesNintenActions)" />
    public interface IMapaAccionesNintenActions
    {
        /// <summary>
        /// Method invoked when associated input action "Movimiento" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMovimiento(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SaltoInteraccionConfirmar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSaltoInteraccionConfirmar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DistanciaCancelar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDistanciaCancelar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Magia" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMagia(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Atacar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAtacar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Escudo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEscudo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FijarDisparar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFijarDisparar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Camara" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamara(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pausa" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPausa(InputAction.CallbackContext context);
    }
}
